# Generated by Django 5.2.11 on 2026-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0003_userprofile_age_userprofile_highest_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ward',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='residents_profiles', to='locations.ward'),
        ),
    ]
