# Generated by Django 5.2.11 on 2026-02-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_lsgi_code'),
        ('profiles', '0004_remove_userprofile_ward_userprofile_wards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='Residential Ward for Citizens', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.ward'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wards',
            field=models.ManyToManyField(blank=True, help_text='Assigned Wards for Field Trainers', related_name='assigned_trainers', to='locations.ward'),
        ),
    ]
