# Generated by Django 5.2.11 on 2026-02-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Official district code', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Official block code', max_length=10, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='locations.district')),
            ],
        ),
        migrations.CreateModel(
            name='LSGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lsgi_type', models.CharField(choices=[('GP', 'Grama Panchayat'), ('MUNICIPALITY', 'Municipality'), ('CORPORATION', 'Corporation'), ('BP', 'Block Panchayat'), ('DP', 'District Panchayat')], max_length=20)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsgis', to='locations.block')),
                ('district', models.ForeignKey(help_text='Direct link for Corporations/Municipalities not under a Block', on_delete=django.db.models.deletion.CASCADE, related_name='lsgis', to='locations.district')),
            ],
            options={
                'verbose_name': 'Local Self Govt Institution',
                'verbose_name_plural': 'LSGIs',
                'unique_together': {('name', 'district', 'lsgi_type')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lsgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.lsgi')),
            ],
            options={
                'ordering': ['lsgi', 'number'],
                'unique_together': {('number', 'lsgi')},
            },
        ),
    ]
