# Generated by Django 5.2.11 on 2026-02-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SAFE_TECH', 'Safe Tech'), ('AI_EDU', 'AI Education'), ('DEED', 'DEED')], max_length=20)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], default='OFFLINE', max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, help_text='Physical location if offline', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'DISTRICT_MASTER_TRAINER'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(help_text='Strict Ward Anchor', on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='locations.ward')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'LSGI_FIELD_TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training_sessions.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'trainer')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(limit_choices_to={'role': 'CITIZEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training_sessions.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'citizen')},
            },
        ),
    ]
