# Generated by Django 5.2.11 on 2026-02-11 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='Strict Ward Anchor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='locations.ward'),
        ),
    ]
