# Generated by Django 5.2.11 on 2026-02-11 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_alter_trainingsession_ward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True, help_text='Link if not uploading file', null=True)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('PPT', 'Presentation'), ('XLS', 'Spreadsheet'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
