# Generated by Django 5.2.11 on 2026-02-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training_sessions.trainingsession'),
        ),
    ]
