# Generated by Django 5.2.11 on 2026-02-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ward_id', models.IntegerField(db_column='ward_id', help_text='Ward ID (Geo Service)')),
                ('category', models.CharField(choices=[('SAFE_TECH', 'Safe Tech'), ('AI_EDU', 'AI Education'), ('DEED', 'DEED')], max_length=20)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], default='OFFLINE', max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, help_text='Physical location if offline', max_length=255)),
                ('created_by_id', models.IntegerField(db_column='created_by_id', help_text='User ID (Auth Service)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.IntegerField(db_column='trainer_id', help_text='Trainer User ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training_sessions.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'trainer_id')},
            },
        ),
    ]
