# Generated by Django 5.2.11 on 2026-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('KSITM_SUPER_ADMIN', 'KSITM Super Admin'), ('LSGD_STATE_ADMIN', 'LSGD State Admin'), ('LSGD_DISTRICT_ADMIN', 'LSGD District Admin'), ('LSGD_BLOCK_ADMIN', 'LSGD Block/Assembly Admin'), ('LSGI_ADMIN', 'LSGI Admin'), ('STATE_SUPER_TRAINER', 'State Level Super Trainer'), ('DISTRICT_MASTER_TRAINER', 'LSGI Master Trainer'), ('BLOCK_TRAINER', 'Block/Assembly Level Trainer'), ('LSGI_FIELD_TRAINER', 'LSGI Field Level Trainer'), ('CITIZEN', 'Citizen')], default='CITIZEN', help_text='User role for RBAC', max_length=50),
        ),
    ]
