# Generated by Django 5.2.11 on 2026-02-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Block Name (Malayalam)'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District Name (Malayalam)'),
        ),
        migrations.AddField(
            model_name='lsgi',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LSGI Name (Malayalam)'),
        ),
        migrations.AddField(
            model_name='ward',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward Name (Malayalam)'),
        ),
    ]
