# Generated by Django 5.2.11 on 2026-02-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_block_name_mal_district_name_mal_lsgi_name_mal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsgi',
            name='code',
            field=models.CharField(blank=True, help_text='LSGI Code (LBCode)', max_length=20, null=True, unique=True),
        ),
    ]
