# Generated by Django 5.2.11 on 2026-02-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_lsgi_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lsgi',
            options={'ordering': ['name'], 'verbose_name': 'Local Self Govt Institution', 'verbose_name_plural': 'LSGIs'},
        ),
    ]
