# Generated by Django 5.2.11 on 2026-02-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(help_text='ID from Session Service')),
                ('citizen_id', models.IntegerField(help_text='ID from Auth Service')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by_id', models.IntegerField(help_text='Trainer ID who marked attendance', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='attendance__session_ad8f43_idx'), models.Index(fields=['citizen_id'], name='attendance__citizen_e0d8be_idx')],
                'unique_together': {('session_id', 'citizen_id')},
            },
        ),
    ]
